export const GET_BASE_CURRENCY_REQUESTED = 'GET_BASE_CURRENCY_REQUESTED';
export const GET_BASE_CURRENCY_SUCCESS = 'GET_BASE_CURRENCY_SUCCESS';
export const GET_BASE_CURRENCY_FAILED = 'GET_BASE_CURRENCY_FAILED';
export const GET_EXCHANGE_RATES_REQUESTED = 'GET_EXCHANGE_RATES_REQUESTED';
export const GET_EXCHANGE_RATES_SUCCESS = 'GET_EXCHANGE_RATES_SUCCESS';
export const GET_EXCHANGE_RATES_FAILED = 'GET_EXCHANGE_RATES_FAILED';
export const SET_BASE_CURRENCY = 'SET_BASE_CURRENCY';