//base currency
export const GET_BASE_CURRENCY_REQUESTED = 'GET_BASE_CURRENCY_REQUESTED';
export const GET_BASE_CURRENCY_SUCCESS = 'GET_BASE_CURRENCY_SUCCESS';
export const GET_BASE_CURRENCY_FAILED = 'GET_BASE_CURRENCY_FAILED';
export const SET_BASE_CURRENCY = 'SET_BASE_CURRENCY';
//exchange rates
export const GET_EXCHANGE_RATES_REQUESTED = 'GET_EXCHANGE_RATES_REQUESTED';
export const GET_EXCHANGE_RATES_SUCCESS = 'GET_EXCHANGE_RATES_SUCCESS';
export const GET_EXCHANGE_RATES_FAILED = 'GET_EXCHANGE_RATES_FAILED';
//supported codes
export const GET_SUPPORTED_CODES_REQUESTED = 'GET_SUPPORTED_CODES_REQUESTED';
export const GET_SUPPORTED_CODES_SUCCESS = 'GET_SUPPORTED_CODES_SUCCESS';
export const GET_SUPPORTED_CODES_FAILED = 'GET_SUPPORTED_CODES_FAILED';
//get conversion value
export const GET_CONVERSION_VALUE_REQUESTED = 'GET_CONVERSION_VALUE_REQUESTED';
export const GET_CONVERSION_VALUE_SUCCESS = 'GET_CONVERSION_VALUE_SUCCESS';
export const GET_CONVERSION_VALUE_FAILED = 'GET_CONVERSION_VALUE_FAILED';
